services:
  - type: web
    name: laravel-app
    env: php               # ✅ Correct environment
    region: oregon
    plan: free
    autoDeploy: true

    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan migrate --force
      npm install
      npm run build

    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:YOUR_GENERATED_APP_KEY
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
